"""Initial schema

Revision ID: b1dda8e2dda1
Revises: 
Create Date: 2026-01-23 22:59:14.004356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b1dda8e2dda1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('patient_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_deleted_at'), 'patients', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_is_deleted'), 'patients', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patients_patient_number'), 'patients', ['patient_number'], unique=True)
    op.create_table('payrolls',
    sa.Column('payroll_number', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrolls_created_at'), 'payrolls', ['created_at'], unique=False)
    op.create_index(op.f('ix_payrolls_deleted_at'), 'payrolls', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payrolls_id'), 'payrolls', ['id'], unique=False)
    op.create_index(op.f('ix_payrolls_is_deleted'), 'payrolls', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payrolls_payroll_number'), 'payrolls', ['payroll_number'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('doctors',
    sa.Column('doctor_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('department_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_deleted_at'), 'doctors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_doctors_doctor_number'), 'doctors', ['doctor_number'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_is_deleted'), 'doctors', ['is_deleted'], unique=False)
    op.create_table('employees',
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('department_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('transaction_number', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_created_at'), 'financial_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_financial_transactions_deleted_at'), 'financial_transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_is_deleted'), 'financial_transactions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_number'), 'financial_transactions', ['transaction_number'], unique=True)
    op.create_table('insurances',
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('coverage_start_date', sa.Date(), nullable=False),
    sa.Column('coverage_end_date', sa.Date(), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deductible', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('copay_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('patient_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurances_created_at'), 'insurances', ['created_at'], unique=False)
    op.create_index(op.f('ix_insurances_deleted_at'), 'insurances', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_insurances_id'), 'insurances', ['id'], unique=False)
    op.create_index(op.f('ix_insurances_is_deleted'), 'insurances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_insurances_policy_number'), 'insurances', ['policy_number'], unique=True)
    op.create_table('targets',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('department_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('assigned_to_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_created_at'), 'targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_targets_deleted_at'), 'targets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.create_index(op.f('ix_targets_is_deleted'), 'targets', ['is_deleted'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('role_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_number', sa.String(length=20), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('patient_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('doctor_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('department_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointments_deleted_at'), 'appointments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_is_deleted'), 'appointments', ['is_deleted'], unique=False)
    op.create_table('attendances',
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('employee_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_attendance_date'), 'attendances', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendances_created_at'), 'attendances', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendances_deleted_at'), 'attendances', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_is_deleted'), 'attendances', ['is_deleted'], unique=False)
    op.create_table('payslips',
    sa.Column('payslip_number', sa.String(length=20), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_allowances', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('employee_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('payroll_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_created_at'), 'payslips', ['created_at'], unique=False)
    op.create_index(op.f('ix_payslips_deleted_at'), 'payslips', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_index(op.f('ix_payslips_is_deleted'), 'payslips', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payslips_payslip_number'), 'payslips', ['payslip_number'], unique=True)
    op.create_table('salary_structures',
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('housing_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transport_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('medical_allowance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_allowances', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_deduction', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurance_deduction', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('employee_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_created_at'), 'salary_structures', ['created_at'], unique=False)
    op.create_index(op.f('ix_salary_structures_deleted_at'), 'salary_structures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_index(op.f('ix_salary_structures_is_deleted'), 'salary_structures', ['is_deleted'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('patient_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('appointment_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoices_deleted_at'), 'invoices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    op.create_table('work_queues',
    sa.Column('queue_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entity_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('appointment_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('assigned_to_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_queues_created_at'), 'work_queues', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_queues_deleted_at'), 'work_queues', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_work_queues_id'), 'work_queues', ['id'], unique=False)
    op.create_index(op.f('ix_work_queues_is_deleted'), 'work_queues', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_work_queues_queue_number'), 'work_queues', ['queue_number'], unique=True)
    op.create_table('invoice_items',
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_created_at'), 'invoice_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_invoice_items_deleted_at'), 'invoice_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_is_deleted'), 'invoice_items', ['is_deleted'], unique=False)
    op.create_table('payments',
    sa.Column('payment_number', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft deleted'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Boolean flag for soft delete status'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_deleted_at'), 'payments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_is_deleted'), 'payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_is_deleted'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_deleted_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_items_is_deleted'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_deleted_at'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_created_at'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_work_queues_queue_number'), table_name='work_queues')
    op.drop_index(op.f('ix_work_queues_is_deleted'), table_name='work_queues')
    op.drop_index(op.f('ix_work_queues_id'), table_name='work_queues')
    op.drop_index(op.f('ix_work_queues_deleted_at'), table_name='work_queues')
    op.drop_index(op.f('ix_work_queues_created_at'), table_name='work_queues')
    op.drop_table('work_queues')
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_deleted_at'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_salary_structures_is_deleted'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_deleted_at'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_created_at'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_payslips_payslip_number'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_is_deleted'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_deleted_at'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_created_at'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_attendances_is_deleted'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_deleted_at'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_created_at'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_attendance_date'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_appointments_is_deleted'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_deleted_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_targets_is_deleted'), table_name='targets')
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_deleted_at'), table_name='targets')
    op.drop_index(op.f('ix_targets_created_at'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_insurances_policy_number'), table_name='insurances')
    op.drop_index(op.f('ix_insurances_is_deleted'), table_name='insurances')
    op.drop_index(op.f('ix_insurances_id'), table_name='insurances')
    op.drop_index(op.f('ix_insurances_deleted_at'), table_name='insurances')
    op.drop_index(op.f('ix_insurances_created_at'), table_name='insurances')
    op.drop_table('insurances')
    op.drop_index(op.f('ix_financial_transactions_transaction_number'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_is_deleted'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_deleted_at'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_created_at'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_doctors_is_deleted'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_number'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_deleted_at'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_payrolls_payroll_number'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_is_deleted'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_id'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_deleted_at'), table_name='payrolls')
    op.drop_index(op.f('ix_payrolls_created_at'), table_name='payrolls')
    op.drop_table('payrolls')
    op.drop_index(op.f('ix_patients_patient_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_is_deleted'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_deleted_at'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
